### ISSUE TITLE
Option of a full screen view for hub maps

### ISSUE THREAD

**Issue by crowdcoverllc** [maphubs/maphubs#65] opened 2016-03-22 16:43 UTC

**Comment by kriscarle** [comment] 2016-03-22 17:23
This is a duplicate of #17

**Comment by kriscarle** [comment] 2016-03-22 17:24
Do you mean hiding the banner and layer list on the hub map page? http://maindombe.maphubs.com/map

**Comment by kriscarle** [comment] 2016-03-24 22:53
we resolved this by improving the hub links and added a "view larger" button

**Closed** 2016-03-24 22:54 UTC
Labels: enhancement
